sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
